### ISSUE TITLE
Testing Notification Sync

### ISSUE THREAD

**Issue by elfdie00475** [alexa/avs-device-sdk#1248]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Hi, all
I tested the notification sync and I had the problem.
Notification sync test need two AVS devices, one of my devices is Echo Plus and the other is SampleApp
When I asked my notification by using Echo Plus, I had seen that notification state was closed. In expected result, the notification state of SampleApp was changed to off, but it did not happen.

So, I need some help to check the problem. Here is the log:
[log1.TXT](https://github.com/alexa/avs-device-sdk/files/2908361/log1.TXT)
[log2.TXT](https://github.com/alexa/avs-device-sdk/files/2908362/log2.TXT)
[log3.TXT](https://github.com/alexa/avs-device-sdk/files/2908363/log3.TXT)

In log1, this is SampleApp' s state before the test, the NOTIFICATION INDICATOR STATE is off.
In log2, this is SampleApp's state after creating a notification by using Echo Plus and turning SampleApp back, the NOTIFICATION INDICATOR STATE is on.
In log3, this is SampleApp's state after closing the notification state by using Echo Plus and turning SampleApp back, the NOTIFICATION INDICATOR STATE is still on. 

## What is the expected behavior?

Following the steps, the notification state is off.

## What behavior are you observing?

The notification state did not change back to off after the steps.

## Provide the steps to reproduce the issue, if applicable:

Device1: SampleApp 
Device2: other AVS device

Step:
1. Run the device1 and check the notification state is off.
2. Turn off the device1 and check the device's state is offline in Alexa App.
3. Use device2 to create the notification.
4. Run the device1 and check the notification state is on.
5. Turn off the device1 again.
6. Ask notification by using device2.
7. Check the notification state is changed to off on device2.
8. Run the device1 again and check the notification state.

### What version of the AVS Device SDK are you using?
      <1.11.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more: arm-linux embedded

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kjkh** [comment]
Hi @elfdie00475,

Thanks for bringing this to our attention. According to the UX guidelines, the SetIndicator directive should not have been sent in log2.txt since your device was in DoNotDisturb mode. However, there was a bug in 1.11 in which the DoNotDisturb value on the device may go out of sync in certain situations. This was fixed in 1.12.

We will follow up with the cloud. In the meantime, would it be possible to upgrade to 1.12 and see if that fixes your issue?

**Comment by elfdie00475** [comment]
Hi @kjkh, 

Thanks your reply and tell about the DoNotDisturb behavior.

Actually, I don't handle or test the DoNotDisturb feature until now, so I can sure that DoNotDisturb is not being enabled by voice or manual.
I only test by following the steps I provided.

I still follow your suggestion to test this issue in 1.12.

Thanks.

**Comment by elfdie00475** [comment]
Hi all,

I try 1.12 by following the same steps, it still happen.

Thanks~~

**Comment by elfdie00475** [comment]
Hi,

I know SetIndicator and ClearIndicator directive event always send from AVS cloud to my device, so notification will use last status after re-running Sample APP if AVS cloud does not send new directive event to my device.
In time, I think AVS cloud does not send new notification directive event to my device when I re-run the Sample App. 
So, I want to know  that have any functions can request the AVS cloud to update notification states in SDK?

Thanks~~

**Comment by elfdie00475** [comment]
Hi all, me again

We take this issue to ask our AVS solutions architect. And this is his answer:
Looking at your log, you are right.  The cloud should send a clearIndicator directive at startup, but that doesn’t happen until line 997 [(in notification_log3.TXT)](https://github.com/alexa/avs-device-sdk/files/3210153/notification_log3.TXT).  That is right in the midst of a SpeechRecognize event, so I am thinking you used a voice command to ask about notifications. 

Hope for helpful.
Thanks~~

**Comment by kclchan** [comment]
This issue is fixed in v1.15 of the SDK.
