### ISSUE TITLE
Unable to hear Alexa's response

### ISSUE THREAD

**Issue by 9s2j6** [alexa/avs-device-sdk#1643]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I cannot hear what Alexa is saying. The script says she is speaking, and I can tell she can hear me. When I asked "Can you hear me", it printed "can you hear me" in the script. Doing rec test.wav and then aplay test.wav confirmed that both the mic and speakers work outside of the AVS SDK.

## What is the expected behavior?
Alexa audibly responds to what I have said.

## What behavior are you observing?
The script says Alexa is speaking but no sound is produced.

## Provide the steps to reproduce the issue, if applicable:
Using a brand new copy of Raspbian from NOOBS
Followed [this](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi.html#set-up-your-configuration-file) tutorial
After looking over [this](https://github.com/alexa/avs-device-sdk/issues/534) issue, I realized I did not have gstreamer-tools installed and installed it. I ran the test scripts and I only get sound from the first one.
I also tried to change the line in MediaPlayer.cpp as described and the line appears to have moved/changed.

### What version of the AVS Device SDK are you using?
      1.18.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop

- [X] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:
- [X] Raspbian Buster (NOOBS install on Raspberry Pi)

**Comment by caleighatamazon** [comment]
Can you please provide us the full DEBUG9 logs, as well as the complete cmake command you used to build the SDK? Let me know if you need help with this.

**Comment by 9s2j6** [comment]
Here you go!
[log.txt](https://github.com/alexa/avs-device-sdk/files/4339964/log.txt)

**Comment by dhpp** [comment]
Hi @9s2j6 - thanks for the log.  Firstly, it shows a lot of alsa mis-configuration trace at the start, which usually means something is not right with either your audio stack or your microphone.  Did you search on these forums for similar issues (and there are many, for example #1413 ) and how they were addressed?

Please also refer to our dependencies page [here](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/dependencies.html#core-music-provider) and [here](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/dependencies.html#sample-app), in particular the GStreamer plugins and PortAudio library.

Let us know if that helps.

**Comment by 9s2j6** [comment]
Hi @dhpp, I have installed the dependencies as shown above on the dependencies page and on issue #1413 and rebuilt the script but I am still getting the same errors.

**Comment by kjkh** [comment]
Hi @9s2j6,

Are you able to get other audio playback on the Pi? The first step would be to narrow down if this is an SDK issue or if it's an issue related to the Pi.

One common problem is that on the Pi, you need to configure the SDK gstreamer pipeline to use ALSA as the sink. This can be done by modifying AlexaClientSDKConfig.json and uncommenting the following:

```
    // "gstreamerMediaPlayer":{
    //     "outputConversion":{
    //         "rate":16000,
    //         "format":"S16LE",
    //         "channels":1
    //     },
    //     "audioSink":"autoaudiosink"
    // },

```

**Comment by 9s2j6** [comment]
Hi @kjkh,
Thanks for reaching out.
I am able to get other audio playback on the Pi. Running rec test.wav and then aplay test.wav plays the audio I just recorded, so the mic and speakers are working.

Uncommenting the lines you mentioned in AlexaClientSDKConfig.json threw two new errors, followed by "Failed to create to SampleApplication":
`2020-04-05 00:17:43.807 [  1] I sdkVersion: 1.18.0
configFile ./Integration/AlexaClientSDKConfig.json
2020-04-05 00:17:43.818 [  1] C SampleApplication:Failed to initialize SDK!
2020-04-05 00:17:43.818 [  1] C SampleApplication:Failed to initialize SampleApplication
Failed to create to SampleApplication!`

**Comment by atmatthewat** [comment]
Undo the changes to AlexaClientSDKConfig.json and then try
`sudo apt install gstreamer1.0-tools gstreamer1.0-alsa`
Please update if that is sufficient to fix the issue

**Comment by 9s2j6** [comment]
Hi @atmatthewat,
I have undone the changes to AlexaClientSDKConfig.json and run the install command but I both are already on my Pi and the newest version.

**Comment by atmatthewat** [comment]
Are you able to hear the test tone if you execute
`gst-launch-1.0 audiotestsrc ! autoaudiosink`

**Comment by 9s2j6** [comment]
Hi @atmatthewat 
I have executed the test tone command but I didn't hear anything.

**Comment by atmatthewat** [comment]
Does the text output from the test tone suggest it is playing or that it encountered an error?

Do you have speakers/headphone attached to the 3.5mm jack on the Raspberry Pi?

**Comment by atmatthewat** [comment]
Pasting the output of
`gst-launch-1.0 -v audiotestsrc ! autoaudiosink`
might help get to the bottom of this

**Comment by 9s2j6** [comment]
Hi @atmatthewat,
I do have speakers attached to the 3.5mm jack and I have tested that they work.
The text output does not suggest an error, but here it is anyway:
> Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Redistribute latency...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstAudioSinkClock
^Chandling interrupt.
Interrupt: Stopping pipeline ...
Execution ended after 0:00:05.451860780
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...`

**Comment by atmatthewat** [comment]
At this point the problem appears to be outside of the AVS Device SDK. You may want to pursue this issue with the gstreamer community.

In the meantime, you might try removing and reinstalling `gstreamer1.0-tools` and `gstreamer1.0-alsa` using `apt-get purge` and `apt-get install` for each, or starting the installation tutorial from scratch on a new Raspbian and then installing gstreamer1.0-tools and gstreamer1.0-alsa.

Another thing to try is to test the output with `gst-launch-1.0 -v audiotestsrc ! autoaudiosink` after ensuring that you have no other audio devices installed (remove the USB microphone and any other USB audio devices from the system and reboot prior to this test)

**Comment by caleighatamazon** [comment]
I'm going to close this due to inactivity, but please feel free to comment on the issue or open a new one if you continue to have problems.

**Comment by 9s2j6** [comment]
Hi,
Sorry for the late reply.
Could you please direct me to where I can contact the gstreamer community or open an issue?
