### ISSUE TITLE
AVS SDK 1.6:: Context Manager Timeout - Long range test

### ISSUE THREAD

**Issue by adpandit** [alexa/avs-device-sdk#778]
Hi, 

We are seeing contextRequestErrorOccurred,error=STATE_PROVIDER_TIMEDOUT. If context fetch done not happen correctly, none of the Capability Agents seem to receive a callback which would *not* allow them to do their routine. E.g. Send Recognize Event, Play Speech, Audio etc. The only way out is to restart the application. 

We had a long range music test going and music stopped after 4 hours. We attempted barge in during a music playback multiple times. A snippet of the log is shown below. 

>> last recognize. 
2018-06-06 23:53:41.530 [  a] 0 EventBuilder:buildJsonEventString:messageId=6318c25c-5d37-47ff-ab0f-7fec23f414d8,namespace=SpeechRecognizer,name=Recognize

>> could not send a recognize event as it failed during construction. 
2018-06-06 23:53:46.530 [  f] E SpeechSynthesizer:onFocusChangeFailed:reason=stateChangeTimeout,messageId=5d2f11a2-9d74-4bca-91da-f27d8507f834
2018-06-06 23:53:46.531 [  f] 0 EventBuilder:buildJsonEventString:messageId=95ca4a69-8273-4867-be26-83388bcfbf52,namespace=System,name=ExceptionEncountered

>> once this has happened (probably because of alexa disconnect). 
2018-06-06 23:55:49.685 [105] 0 PostConnectSynchronize:onServerSideDisconnect()
2018-06-06 23:55:49.686 [105] 0 PostConnectSynchronize:PostConnectSynchronizer::doShutdown().
2018-06-06 23:55:49.687 [105] 0 MessageRouter:connectionStatusChanged:reason=SERVER_SIDE_DISCONNECT,newStatus=PENDING
2018-06-06 23:55:49.692 [105] 9 HTTP2Transport:setupDownchannelStream:url=https\://avs-alexa-na.amazon.com/v20160207/directives

>>no recovery possible after context manager gets in the time out loop. 
2018-06-06 23:55:51.698 [  7] E ContextManager:updateStatesLoopFailed:reason=stateProviderTimedOut
2018-06-06 23:55:51.698 [  7] E PostConnectSynchronize:contextRetrievalFailed:reason=contextRequestErrorOccurred,error=STATE_PROVIDER_TIMEDOUT

**Comment by scotthea-amazon** [comment]
Hello adpandit,

Would you please attach (preferred over copying the text in to the thread) a complete log so that we have more data with which to determine how the state provider has gotten stuck?

Thank you,
-SWH

**Comment by BobXLiu** [comment]
Hi @scotthea-amazon,

We have also occurred this issue. The below is log information, please help check it.
Thanks!
SDK 1.7.1
[stateProviderTimedOut.log](https://github.com/alexa/avs-device-sdk/files/2153458/stateProviderTimedOut.log)

**Comment by justy0714** [comment]
Hi @scotthea-amazon,

SDK 1.8.1

We have also run into the same issue. Attached is the detailed log messages. Please help to check it.

As the log indicates, at line #110174, MessageRouter suddenly appeared "connectionStatusChanged" with reason "SERVER_SIDE_DISCONNECT" and it never recovered  to Connected from Disconnected.

And then, ContextManager continued to show "stateProviderTimedOut"

[stateProviderTimedOut_0804.log](https://github.com/alexa/avs-device-sdk/files/2261035/stateProviderTimedOut_0804.log)

**Comment by mavamazon** [comment]
Hi.
Thank you for your input, @BobXLiu and @justy0714 !
Could you please edit `CapabilityAgents/SpeechSynthesizer/src/SpeechSynthesizer.cpp` file at line `234`:
Was:
```
    std::lock_guard<std::mutex> lock(m_mutex);
    auto state = m_currentState;
    m_executor.submit([this, state, stateRequestToken]() { executeProvideState(state, stateRequestToken); });
```
Should be:
```
    m_executor.submit([this, stateRequestToken]() {
        std::lock_guard<std::mutex> lock(m_mutex);
        executeProvideState(m_currentState, stateRequestToken);
    });
```

This should let you avoid the reconnection problem. I hope the fix is going to be in the next release.

**Comment by kclchan** [comment]
Hi, please try again with v1.9.  We have fixed an issue related to stateProviderTimedOut.

**Comment by zeusshuang** [comment]
Hi @kclchan ,

We got a failed case on 1.9.  Originally, we think it may be case #948 issue, but to look into the logs, it seems this case.

The log is huge, but you can check it from line-10090, it seems the first failed due to Internet disconnect, it's fine. but after Internet returned, it still failed and I saw sever side error. 
(line-10763) we leave a monitor script log here to indicate the case#778 issue.
While the Internet is good but router message is lost, we dump it (just for our internal debug, but it indicates this case#778 issue)

[avs_dbg_log-1008.zip](https://github.com/alexa/avs-device-sdk/files/2467307/avs_dbg_log-1008.zip)

**Comment by kclchan** [comment]
Hi @zeusshuang,

Based on your logs, you are not seeing the stateProviderTimedOut problem, but rather it's getting a getHttpContentTimeout.  In the InternetConnectionMonitor, we periodically fetch content from an url to check if internet connection is ok or not.  It seems that during your test, that url is down leading to the error message.  Are you seeing any other issues with the SDK other than the error log?

**Comment by zeusshuang** [comment]
Hi @kclchan ,

No, it's running about 3 days and suddenly failed and we wait for hours but not return to normal.
At the same time, the DUT will also checking Internet connection (eg. ping 8.8.8.8) and working, and it seems the refresh token process is still working.  
The only thing may related to this case is that while it became abnormal, the Internet ever disconnected for minutes and return. (we traced our system log and found the Internet ever disconnected before AVS stuck)

Restart AVS will let it become normal.

**Comment by kclchan** [comment]
Hi @zeusshuang,
Just want to clarify, besides the getHttpContentTimeout error logs, do you see anything functionally wrong with the DUT?  From what I see in the logs, I still see the DUT responding to utterance and were able to play music.  So just want to make sure and see if there's something that I am missing.  Thanks!

**Comment by zeusshuang** [comment]
Hi @kclchan ,

Sorry for the confused.

 I double check with the tester, after line#10090, and it continues to run hours, but it still cannot be triggered by voice and no response, but a somehow it can response by trigger command (cmd : t), but voice command failed. MIC should be okay due to it can Q&A at that moment.

**Comment by kclchan** [comment]
Hi @zeusshuang, sorry for not getting back soon on this.  From the log:
```
2018-10-08 03:26:34.177 [ 37] I KeywordObserver:Keyword wake-up detected:InternetConnectionStatus=0
2018-10-08 03:26:34.177 [ 37] I KeywordObserver:Keyword wake-up detected:AuthState=1
2018-10-08 03:26:34.177 [ 37] I KeywordObserver:avsAnalytic:triggerCountByVoice=34
2018-10-08 03:26:34.178 [ 37] 0 KeywordObserver:###onKeyWordDetected KeywordObserver.cpp###:m_client->isConnected=1
2018-10-08 03:26:34.204 [  b] 0 DialogUXStateAggregator:transitionFromThinkingTimedOut
2018-10-08 03:26:34.205 [  b] 0 DialogUXStateAggregator:setState:from=THINKING,to=IDLE
[2018-10-08 11:26:34] AVS:KeywordObserver:Set led_color=LED_LP5562_RED as WiFi backhaul is broken
```
It seems the wakeword failed because of InternetConnectionStatus=0.  Is this still an open issue?  If not, would it be able to close this?

**Comment by zeusshuang** [comment]
Hi @kclchan ,

We can trace the case at #948, and closed this case for my issue, but this case is not created by me :)
